// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"integration-suricata-ndpi/internal/app"
)

// Injectors from wire.go:

func InitializeIntegrationService(configPath string) (app.Service, error) {
	service, err := newIntegrationService(configPath)
	if err != nil {
		return nil, err
	}
	return service, nil
}

func InitializeHostAgentService(opts HostAgentOptions) (app.Service, error) {
	service, err := newHostAgentService(opts)
	if err != nil {
		return nil, err
	}
	return service, nil
}
