// Code generated by Wire. DO NOT EDIT.

package wire

import (
	"time"

	"integration-suricata-ndpi/integration"
	"integration-suricata-ndpi/internal/app"
	"integration-suricata-ndpi/internal/config"
	"integration-suricata-ndpi/pkg/fsutil"
	"integration-suricata-ndpi/pkg/hostagent"
	"integration-suricata-ndpi/pkg/systemd"
)

func InitializeIntegrationService(configPath string) (app.Service, error) {
	return newIntegrationService(configPath)
}

func InitializeHostAgentService(opts HostAgentOptions) (app.Service, error) {
	return newHostAgentService(opts)
}

type HostAgentOptions struct {
	ConfigPath      string
	SocketPath      string
	SuricataConfig  string
	NDPIPluginPath  string
	SystemdUnit     string
	SystemctlPath   string
	RestartTimeout  time.Duration
	ShutdownTimeout time.Duration
}

func newIntegrationService(configPath string) (app.Service, error) {
	return integration.NewRunner(configPath, nil, fsutil.OSFS{}), nil
}

func newHostAgentService(opts HostAgentOptions) (app.Service, error) {
	cfg, err := config.Load(opts.ConfigPath)
	if err != nil {
		return nil, err
	}

	suricataCfgPath := opts.SuricataConfig
	if suricataCfgPath == "" {
		p, err := integration.FirstExistingPath(cfg.Suricata.ConfigCandidates)
		if err != nil {
			return nil, err
		}
		suricataCfgPath = p
	}

	ndpiPluginPath := opts.NDPIPluginPath
	if ndpiPluginPath == "" {
		ndpiPluginPath = cfg.Paths.NDPIPluginPath
	}

	unit := opts.SystemdUnit
	if unit == "" {
		unit = cfg.System.SuricataService
	}

	systemctlPath := opts.SystemctlPath
	if systemctlPath == "" {
		systemctlPath = cfg.System.Systemctl
	}

	deps := hostagent.Deps{
		SocketPath:      opts.SocketPath,
		SuricataCfgPath: suricataCfgPath,
		NDPIPluginPath:  ndpiPluginPath,
		SuricataUnit:    unit,
		RestartTimeout:  opts.RestartTimeout,
		SystemctlPath:   systemctlPath,
		Systemd:         systemd.NewManager(systemctlPath, nil),
		FS:              fsutil.OSFS{},
	}

	return hostagent.New(deps)
}
